name: Build (Windows)

on:
  push:
  pull_request:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.17'

    - name: Build eac3to-wrapper
      shell: bash
      run: |
        go build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: ./*.exe
