name: Build (Windows)

on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Setup Go
      uses: actions/setup-go@v7
      with:
        go-version: '1.26.5'

    - name: Test eac3to-wrapper
      shell: pwsh
      run: go test ./...

    - name: Build eac3to-wrapper
      shell: pwsh
      run: go build -o eac3to-wrapper.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: release
        path: eac3to-wrapper.exe
        if-no-files-found: error
